apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
    app: java-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "java-app.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}

